version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - (Get-ECRLoginCommand).Password | docker login --username AWS --password-stdin 796662406405.dkr.ecr.ap-south-1.amazonaws.com
#       - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 796662406405.dkr.ecr.ap-south-1.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG 796662406405.dkr.ecr.ap-south-1.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG      
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 796662406405.dkr.ecr.ap-south-1.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
